// simpleicons.org slugs — all tinted in brand gold (#cfab67)
// Only slugs verified to exist on simpleicons are used
const G = 'cfab67';
const ic = (slug: string) => `https://cdn.simpleicons.org/${slug}/${G}`;

export const LOGOS = [
  // Big Tech
  ic('apple'),
  ic('google'),
  ic('meta'),
  ic('netflix'),
  ic('nvidia'),
  ic('tesla'),
  ic('intel'),
  ic('amd'),
  ic('qualcomm'),
  ic('samsung'),
  ic('sony'),
  ic('palantir'),
  ic('shopify'),
  ic('spotify'),
  ic('uber'),
  ic('airbnb'),
  ic('zoom'),
  ic('dropbox'),
  ic('x'),
  ic('snapchat'),
  ic('pinterest'),
  ic('reddit'),
  ic('discord'),
  ic('twitch'),
  ic('wordpress'),
  ic('figma'),
  ic('notion'),
  // Finance
  ic('visa'),
  ic('mastercard'),
  ic('paypal'),
  ic('stripe'),
  ic('coinbase'),
  ic('revolut'),
  ic('klarna'),
  ic('wise'),
  // Auto
  ic('volkswagen'),
  ic('bmw'),
  ic('toyota'),
  ic('honda'),
  ic('hyundai'),
  // Consumer / Retail
  ic('starbucks'),
  ic('nike'),
  ic('adidas'),
  ic('ikea'),
  ic('zara'),
  ic('cocacola'),
  // Cloud / SaaS
  ic('cloudflare'),
  ic('datadog'),
  ic('snowflake'),
  ic('mongodb'),
  ic('atlassian'),
  ic('github'),
  ic('gitlab'),
  ic('docker'),
  ic('kubernetes'),
  ic('postgresql'),
  ic('redis'),
  ic('elastic'),
  ic('vercel'),
  ic('digitalocean'),
  // Semiconductor / Hardware
  ic('arm'),
  ic('siemens'),
];
